<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://suik.erto.transinfocom.ru/service" xmlns:ns3="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://service.suik.erto.transinfocom.ru/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ErtoServiceImplService" targetNamespace="http://service.suik.erto.transinfocom.ru/">
  <wsdl:import location="ErtoServiceApi_3_0.wsdl" namespace="http://suik.erto.transinfocom.ru/service">
    </wsdl:import>
  <wsdl:binding name="ErtoServiceImplServiceSoapBinding" type="ns1:ErtoServiceApi">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="loadData">
      <soap:operation soapAction="http://suik.erto.transinfocom.ru/service/loadData" style="document"/>
      <wsdl:input name="loadData">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="loadDataResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="TiServerSoapException">
        <soap:fault name="TiServerSoapException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ErtoServiceImplService">
    <wsdl:port binding="tns:ErtoServiceImplServiceSoapBinding" name="ErtoServiceImplPort">
      <soap:address location="http://localhost:8080/ros/services/ErtoServiceImplPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
